### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by eusebiu** [jerryhoff/WebGoat.NET#1]
Hello,
I downloaded the zip and tried to install in IIS5.1 XP with .NET 4.0 and I get this error:
http://localhost/WebGoat.NET/Default.aspx ->
Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 

Parser Error Message: Could not load file or assembly 'Mono.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.

Source Error: 

Line 64:                    connectionStringName="SQLiteDbConnection"
Line 65:                    name="SQLiteRoleProvider" 
Line 66:                    type="TechInfoSystems.Data.SQLite.SQLiteRoleProvider, TechInfoSystems.Data.SQLiteProvider" />
Line 67:            </providers>
Line 68:        </roleManager>

Should I install Mono also?

**Comment by raybeorn** [comment]
Closing. Not sure if this is still relevant since it is 10 months old. Please re-open if issue is happening with latest version.
