### ISSUE TITLE
stored XSS lesson vuln to SQLi

### ISSUE THREAD

**Issue by bachrach44** [jerryhoff/WebGoat.NET#4]
The stored XSS lesson is also vulnerable to SQL injection. I don't know if this is by design or not (bonus vulnerabilities!) but if not we should move to a prepared statement in MySqlDbProvider.cs

**Comment by raybeorn** [comment]
We know about this issue, it is by design. Also, I am going to try to start pushing some more lessons from the new-lessons branch to the master branch. Let us know if you find any more issues.  

Thanks,
-Ray L.
