### ISSUE TITLE
how to run webgoat.net

### ISSUE THREAD

**Issue by sakti** [jerryhoff/WebGoat.NET#5]
is there documentation on how to run webgoat.net?

**Comment by sakti** [comment]
i found installation steps on Ubuntu, in here http://www.frameloss.org/2012/05/23/installing-webgoat-net-using-apache-on-ubuntu/

**Comment by raybeorn** [comment]
Looks like you found install steps. gonna close this but we do need to work on the wiki and have an official install guide.
