### ISSUE TITLE
trace.axd

### ISSUE THREAD

**Issue by jksdua** [jerryhoff/WebGoat.NET#6]
Hi Jerry,

Any way to turn on trace.axd?

I noticed it is disabled in web.config. I tried changing the values there with no luck. Wondering if you know how to turn it on.

Thanks.

**Comment by raybeorn** [comment]
Hello.

You need to change the trace element to look like this 
<trace enabled="true" localOnly="true" pageOutput="false" requestLimit="10" traceMode="SortByTime" />

then goto 
http://127.0.0.1:8081/trace.axd
(or wherever your host is)

If you want page specific traces set pageOutput="true"

-Ray
